{% set name = "tytanic" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tingerrr/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0f046b95b38675ff0004fbafda299e192c0047e48d225cec5ebef2eb24bd57c1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]
  run:
    - openssl  # [linux]

test:
  commands:
    - tt --version

about:
  home: https://github.com/tingerrr/tytanic
  summary: 'A visual regression test runner for typst packages.'
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
