{% set name = "tytanic" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tingerrr/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3cdce856fbe5e6b856214fe55c0f7714340a66ead0979b742c6b0a3d212bb9a5

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]
  run:
    - openssl  # [linux]

test:
  commands:
    - tt --version

about:
  home: https://github.com/tingerrr/tytanic
  summary: 'A visual regression test runner for typst packages.'
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
