schema_version: 1

context:
  name: tytanic
  version: 0.3.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/tingerrr/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: a78bdbcc337d28b85d6b0ba7ac94e2d300cd4c6ebfea59a474d24f6081376b56

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - if: linux
      then: openssl
  run:
    - if: linux
      then: openssl

tests:
  - script:
      - tt --version

about:
  summary: A visual regression test runner for typst packages.
  license: MIT or Apache-2.0
  license_file:
    - LICENSE.MIT
    - LICENSE.Apache-2.0
    - THIRDPARTY_LICENSES.yaml
  homepage: https://github.com/tingerrr/tytanic

extra:
  recipe-maintainers:
    - freundTech
