schema_version: 1

context:
  name: tytanic
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/tingerrr/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 098b831096e0a2e1619a5384e4d7f17ab7fe0327555293793b686fd783b5b7dd

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - if: linux
      then: openssl
  run:
    - if: linux
      then: openssl

tests:
  - script:
      - tt --version

about:
  summary: A visual regression test runner for typst packages.
  license: MIT or Apache-2.0
  license_file:
    - LICENSE.MIT
    - LICENSE.Apache-2.0
    - THIRDPARTY_LICENSES.yaml
  homepage: https://github.com/tingerrr/tytanic

extra:
  recipe-maintainers:
    - freundTech
