schema_version: 1

context:
  name: tytanic
  version: 0.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/tingerrr/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 3cdce856fbe5e6b856214fe55c0f7714340a66ead0979b742c6b0a3d212bb9a5

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - if: linux
      then: openssl
  run:
    - if: linux
      then: openssl

tests:
  - script:
      - tt --version

about:
  summary: A visual regression test runner for typst packages.
  license: MIT or Apache-2.0
  license_file:
    - LICENSE.MIT
    - LICENSE.Apache-2.0
    - THIRDPARTY_LICENSES.yaml
  homepage: https://github.com/tingerrr/tytanic

extra:
  recipe-maintainers:
    - freundTech
